### ISSUE TITLE
Error while building mirage-www on 4.02.1

### ISSUE THREAD

**Issue by amirmc** [mirage/ocaml-conduit#61]
Not sure if this issue belongs here or if it's specific to mirage-www. Note the line that says `Error: Unbound module Conduit_mirage.No_TLS`. I'm rebuilding my switches so will try this again later (I normally use 4.01).

```
$ make
ocamlbuild -use-ocamlfind -pkgs lwt.syntax,conduit.mirage,cow.syntax,cowabloga,cstruct,io-page,io-page.unix,lwt,mirage-clock-unix,mirage-console.unix,mirage-fs-unix,mirage-http,mirage-net-unix,mirage-types,mirage-types.lwt,mirage.runtime,tcpip.stack-direct -tags "syntax(camlp4o),annot,bin_annot,strict_sequence,principal" -tag-line "<static*.*>: -syntax(camlp4o)" -cflag -g -lflags -g,-linkpkg main.native
+ ocamlfind ocamlc -c -g -annot -bin-annot -principal -strict-sequence -package tcpip.stack-direct -package mirage.runtime -package mirage-types.lwt -package mirage-types -package mirage-net-unix -package mirage-http -package mirage-fs-unix -package mirage-console.unix -package mirage-clock-unix -package lwt -package io-page.unix -package io-page -package cstruct -package cowabloga -package cow.syntax -package conduit.mirage -package lwt.syntax -syntax camlp4o -o main.cmo main.ml
File "main.ml", line 89, characters 18-39:
Error: Unbound module Conduit_mirage.No_TLS
Command exited with code 2.
Hint: Recursive traversal of subdirectories was not enabled for this build,
  as the working directory does not look like an ocamlbuild project (no
  '_tags' or 'myocamlbuild.ml' file). If you have modules in subdirectories,
  you should add the option "-r" or create an empty '_tags' file.

  To enable recursive traversal for some subdirectories only, you can use the
  following '_tags' file:

      true: -traverse
      <dir1> or <dir2>: traverse

Compilation unsuccessful after building 20 targets (0 cached) in 00:00:02.
make: *** [main.native] Error 10
```

**Comment by samoht** [comment]
Which version of `conduit` do you have? This should be fixed after an `opam upgrade`

**Comment by amirmc** [comment]
```
$ opam list | grep conduit
conduit                     0.7.2  Network connection library for TCP and SSL
mirage-conduit              2.0.0  Virtual package for the Mirage Conduit transp
```

```
$ opam upgrade
Everything as up-to-date as possible (run with --verbose to show unavailable upgrades).
The following would require downgrades or uninstalls, but you may upgrade them explicitely:
  - cohttp.0.17.0
  - conduit.0.8.2
  - cstruct.1.6.0
  - lwt.2.4.8
  - mirage-conduit.2.1.0
  - mirage-http.2.2.0
```

I should mention that I seem to be on opam 1.2.0 even though the homebrew version should be 1.2.1.  Not sure what's up with my system.

**Comment by amirmc** [comment]
I'm also on the internal solver (since I'm on OSX 10.8.5)

**Comment by mor1** [comment]
(FWIW, check whether you ever did an install of HEAD, subsequently
overtaken by a release -- that was my issue; required a `brew reinstall
opam` to get back onto the latest release.)

On 20 April 2015 at 21:59, Amir Chaudhry <notifications@github.com> wrote:

> $ opam list | grep conduit
> conduit                     0.7.2  Network connection library for TCP and SSL
> mirage-conduit              2.0.0  Virtual package for the Mirage Conduit transp
>
> $ opam upgrade
> Everything as up-to-date as possible (run with --verbose to show unavailable upgrades).
> The following would require downgrades or uninstalls, but you may upgrade them explicitely:
>   - cohttp.0.17.0
>   - conduit.0.8.2
>   - cstruct.1.6.0
>   - lwt.2.4.8
>   - mirage-conduit.2.1.0
>   - mirage-http.2.2.0
>
> I should mention that I seem to be on opam 1.2.0 even though the homebrew
> version should be 1.2.1. Not sure what's up with my system.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/ocaml-conduit/issues/61#issuecomment-94566818>.
>



-- 
Richard Mortier
mort@cantab.net

**Comment by avsm** [comment]
You need to do an `opam update` to get conduit 0.8.1+

**Comment by amirmc** [comment]
Mort, I've been studiously avoiding HEAD for some time.  Mainly in the spirit of bring up the rear (i.e reporting annoyances with ye olde releases).

I just did a `brew reinstall opam --without-aspcud` and the update found the new stuff.  Compiling now.  Anil, I'd already done an `opam update` before the `opam upgrade` you see listed upthread.

**Comment by avsm** [comment]
Try `opam install conduit.0.8.2`?

**Comment by amirmc** [comment]
It installed conduit 0.8.2 -- I assume as part of the `opam upgrade` or during `mirage configure --unix`.  The site now builds so I'm closing this for now.  I doubt I can repro it without having to go back to an older version of opam.

Thanks, folks!

**Comment by samoht** [comment]
and you should be using aspcud!

**Comment by garethr** [comment]
mm, I think I've just run into this too. Building inside a docker container running ubuntu 14.04, using the PPA to install OPAM and OPAM to install mirage.

```
root@7eacea2dc71a:/# mirage --version
2.4.0
root@7eacea2dc71a:/# opam --version
1.2.1
root@7eacea2dc71a:/# opam list
[WARNING] Running as root is not recommended
# Installed packages for system:
base-bigarray           base  Bigarray library distributed with the OCaml compiler
base-bytes              base  Bytes library distributed with the OCaml compiler
base-threads            base  Threads library distributed with the OCaml compiler
base-unix               base  Unix library distributed with the OCaml compiler
camlp4         4.02.1+system  Camlp4 is a system for writing extensible parsers for programming languages
cmdliner               0.9.7  Declarative definition of command line interfaces for OCaml
cppo                   1.1.2  Equivalent of the C preprocessor for OCaml programs
crunch                 1.4.0  Convert a filesystem into a static OCaml module
cstruct                1.6.0  access C structures via a camlp4 extension
depext                   0.5  Query and install external dependencies of OPAM packages
io-page                1.5.1  Allocate memory pages suitable for aligned I/O
ipaddr                 2.6.1  IP (and MAC) address representation library
lwt                    2.4.8  A cooperative threads library for OCaml
mirage                 2.4.0  The Mirage library operating system
mirage-types           2.3.0  Module type definitions for Mirage-compatible applications
ocamlfind              1.5.5  A library manager for OCaml
ocplib-endian            0.8  Optimised functions to read and write int16/32/64 from strings and bigarrays, based on new primitives add
ppx_tools             0.99.2  Tools for authors of ppx rewriters and other syntactic tools
re                     1.4.0  RE is a regular expression library for OCaml
sexplib            112.24.01  Library for serializing OCaml values to and from S-expressions
type_conv          112.01.01  Library for building type-driven syntax extensions
```

Error from running `make`:

```
ocamlbuild -use-ocamlfind -pkgs lwt.syntax,conduit.mirage,cstruct,io-page,io-page.unix,lwt,mirage-console.unix,mirage-http,mirage-types,mirage-types.lwt,re.str,tcpip.stack-socket -tags "syntax(camlp4o),annot,bin_annot,strict_sequence,principal" -tag-line "<static*.*>: $syntax(camlp4o)" -cflag -g -lflags -g,-linkpkg main.native
[WARNING] Running as root is not recommended
+ ocamlfind ocamlc -c -g -annot -bin-annot -principal -strict-sequence -package tcpip.stack-socket -package re.str -package mirage-types.lwt -package mirage-types -package mirage-http -package mirage-console.unix -package lwt -package io-page.unix -package io-page -pac$age cstruct -package conduit.mirage -package lwt.syntax -syntax camlp4o -o main.cmo main.ml
File "main.ml", line 53, characters 18-39:
Error: Unbound module Conduit_mirage.No_TLS
Command exited with code 2.
Hint: Recursive traversal of subdirectories was not enabled for this build,
  as the working directory does not look like an ocamlbuild project (no
  '_tags' or 'myocamlbuild.ml' file). If you have modules in subdirectories,
  you should add the option "-r" or create an empty '_tags' file.

  To enable recursive traversal for some subdirectories only, you can use the
  following '_tags' file:

      true: -traverse
      <dir1> or <dir2>: traverse

Compilation unsuccessful after building 6 targets (0 cached) in 00:00:00.
make: *** [main.native] Error 10
```

This was with the following from `make depend`

[NOTE] Package conduit is already installed (current version is 0.7.2).
[NOTE] Package crunch is already installed (current version is 1.4.0).
[NOTE] Package cstruct is already installed (current version is 1.6.0).
[NOTE] Package io-page is already installed (current version is 1.5.1).
[NOTE] Package lwt is already installed (current version is 2.4.8).
[NOTE] Package mirage-conduit is already installed (current version is 2.0.0).
[NOTE] Package mirage-console is already installed (current version is 2.1.3).
[NOTE] Package mirage-http is already installed (current version is 2.2.0).
[NOTE] Package mirage-types is already installed (current version is 2.3.0).
[NOTE] Package mirage-unix is already installed (current version is 2.3.1).
[NOTE] Package re is already installed (current version is 1.4.0).
[NOTE] Package tcpip is already installed (current version is 2.4.3).
[NOTE] Package vchan is already installed (current version is 2.0.2).

**Comment by avsm** [comment]
@garethr was this using the avsm/docker-opam-build container?  I'm wondering what revision your opam-repository was at, since the constraints should be fixed.  Does it happen if you do an `opam update` within the container before trying the build?

**Comment by samoht** [comment]
```
Package conduit is already installed (current version is 0.7.2).
```

This should be 0.8.3 so there is definitely a constraint issue.

**Comment by garethr** [comment]
@avsm @samoht this was using a container I built.

Using `opam update` and `opam upgrade` didn't appear to resolve the issue.

I also tried installing `opam install conduit.0.8.2` but on running configure this appeared to be downgraded.

    downgrade conduit            0.8.2 to 0.7.2

**Comment by samoht** [comment]
Seems that the constraint is due to `mirage-conduit 2.0.0`.

**Comment by samoht** [comment]
I'll add a conflict between old version of `conduit` and `mirage 2.4.0`.

**Comment by garethr** [comment]
@samoht thanks, is there a workaround in the meantime?

**Comment by samoht** [comment]
@garethr mirage-www is now supposed to build fine with opam base repository.
